/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ionicframework.connectedcare848317;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int icon_old=0x7f020001;
        public static final int screen=0x7f020002;
        public static final int splash=0x7f020003;
        public static final int splash_ol=0x7f020004;
        public static final int splash_old=0x7f020005;
        public static final int splash_oldd=0x7f020006;
        public static final int splash_olddd=0x7f020007;
    }
    public static final class string {
        public static final int activity_name=0x7f040002;
        public static final int app_name=0x7f040000;
        public static final int launcher_name=0x7f040001;
    }
    public static final class xml {
        public static final int config=0x7f030000;
    }
}
